### ISSUE TITLE
"Cannot read property 'writes' of undefined"

### ISSUE THREAD

**Issue by bd** [sheepsteak/react-perf-component#1]
This package looks like exactly the tool I need, but I'm running into a problem trying to use it. 

I have `import perf from 'react-perf-component'` and 

```
@perf
export  class FilterPanel extends Component { ...`
```

but this results in the following output and no page load. using the non-decorator syntax also gives a problem. 

```
Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.
Uncaught TypeError: Cannot read property 'writes' of undefined
```

Not really sure what's going on

**Comment by sheepsteak** [comment]
It's probably because this module hasn't been updated for React 0.14 where `import React from 'react/addons'` has been deprecated as they're all in separate components now.

It should be a simple fix but I won't get chance to tackle it until tomorrow.

**Comment by sheepsteak** [comment]
@bd I've made #2 - please see the notes there.
